name: Build

on:
  push:
    branches:
      - main
      - stable
      - release
    tags:
      - v*

jobs:
  publish-hamburg:
    uses: ./.github/workflows/publish.yaml
    with:
      context: hamburg
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}-hamburg
      branch: ${{ github.ref_name }}
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}

  publish-sachsen:
    uses: ./.github/workflows/publish.yaml
    with:
      context: sachsen
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}-sachsen
      branch: ${{ github.ref_name }}
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}
