name: Create and publish Docker image

on:
  push:
    branches:
      - main
      - stable
    tags:
      - v*

jobs:
  publish-hamburg:
    uses: priobike/priobike-graphhopper/.github/workflows/publish.yaml@main
    with:
      context: hamburg
      registry: bikenow.vkw.tu-dresden.de
      image-name: ${{ github.repository }}-hamburg
      branch: ${{ github.ref }}
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}

  publish-sachsen:
    uses: priobike/priobike-graphhopper/.github/workflows/publish.yaml@main
    with:
      context: sachsen
      registry: bikenow.vkw.tu-dresden.de
      image-name: ${{ github.repository }}-sachsen
      branch: ${{ github.ref }}
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}
