name: Build

on:
  push:
    branches:
      - main

jobs:
  publish-sachsen:
    uses: ./.github/workflows/publish.yaml
    with:
      region: sachsen
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}-sachsen
      branch: ${{ github.ref_name }}
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}
